/* Page copy for the site. One block per language, with the same keys in each. */
export const copy = {
  "gl": {
    "intro": "Mapas e ferramentas con datos públicos, para Galicia.",
    "skip": "Saltar aos traballos",
    "sections": "Seccións",
    "works": "Traballos",
    "archive": "Arquivo",
    "about": "Sobre nós",
    "github": "GitHub",
    "archiveNote": "Ferramentas de apoio aos mapas.",
    "redux": "Redux",
    "find": "Buscar",
    "findPlaceholder": "Título, lugar, datos ou ferramenta",
    "findCount": "{n} de {total}",
    "findNone": "Sen resultados",
    "findArchive": "{n} no arquivo",
    "records": "Fichas",
    "record": "Proxecto",
    "openSite": "Abrir o mapa",
    "openRecord": "Abrir",
    "aboutPage": "Sobre",
    "dataPage": "Datos",
    "code": "Código",
    "source": "Datos",
    "built": "Tecnoloxía",
    "updated": "Actualizado",
    "take": "Comentario",
    "more": "Máis",
    "overview": "Resumo",
    "details": "Detalles",
    "continued": "{label}, continuación",
    "pages": "Páxinas",
    "pageOf": "{i} / {n} · {label}",
    "previousPage": "Páxina anterior",
    "nextPage": "Páxina seguinte",
    "shotAlt": "Captura de pantalla de {title}",
    "notice": "Traballo cívico independente a partir de datos públicos. Desde Galicia.",
    "byline": "Feito por <a href=\"{url}\">{name}</a>.",
    "sister": "<a href=\"{url}\">{name}</a> é o proxecto irmán, en Nova York.",
    "sourceCode": "Código fonte",
    "privacy": "Sen cookies nin analítica.",
    "lostTab": "Non atopada",
    "lostTitle": "As nosas desculpas.",
    "lostText": "Esta non é, case con certeza, a páxina que buscabas.",
    "lostHome": "Todos os proxectos están na <a href=\"{home}\">páxina de inicio</a>.",
    "data": "Datos",
    "map": "Mapa",
    "essay": "Ensaio",
    "site": "Sitio",
    "tools": "Ferramentas",
    "journal": "Diario",
    "journalNote": "Textos sobre urbanismo, mobilidade e datos públicos en Galicia.",
    "findJournal": "{n} no diario",
    "read": "Ler",
    "journalSource": "Fonte",
    "journalCoverage": "Cobertura",
    "skipText": "Saltar ao texto",
    "contents": "Contidos"
  },
  "es": {
    "intro": "Mapas y herramientas con datos públicos, para Galicia.",
    "skip": "Saltar a los trabajos",
    "sections": "Secciones",
    "works": "Trabajos",
    "archive": "Archivo",
    "about": "Sobre nosotros",
    "github": "GitHub",
    "archiveNote": "Herramientas de apoyo a los mapas.",
    "redux": "Redux",
    "find": "Buscar",
    "findPlaceholder": "Título, lugar, datos o herramienta",
    "findCount": "{n} de {total}",
    "findNone": "Sin resultados",
    "findArchive": "{n} en el archivo",
    "records": "Fichas",
    "record": "Proyecto",
    "openSite": "Abrir el mapa",
    "openRecord": "Abrir",
    "aboutPage": "Acerca de",
    "dataPage": "Datos",
    "code": "Código",
    "source": "Datos",
    "built": "Tecnología",
    "updated": "Actualizado",
    "take": "Comentario",
    "more": "Más",
    "overview": "Resumen",
    "details": "Detalles",
    "continued": "{label}, continuación",
    "pages": "Páginas",
    "pageOf": "{i} / {n} · {label}",
    "previousPage": "Página anterior",
    "nextPage": "Página siguiente",
    "shotAlt": "Captura de pantalla de {title}",
    "notice": "Trabajo cívico independiente a partir de datos públicos. Desde Galicia.",
    "byline": "Hecho por <a href=\"{url}\">{name}</a>.",
    "sister": "<a href=\"{url}\">{name}</a> es el proyecto hermano, en Nueva York.",
    "sourceCode": "Código fuente",
    "privacy": "Sin cookies ni analítica.",
    "lostTab": "No encontrada",
    "lostTitle": "Nuestras disculpas.",
    "lostText": "Esta no es, casi con toda seguridad, la página que buscabas.",
    "lostHome": "Todos los proyectos están en la <a href=\"{home}\">página de inicio</a>.",
    "data": "Datos",
    "map": "Mapa",
    "essay": "Ensayo",
    "site": "Sitio",
    "tools": "Herramientas",
    "journal": "Diario",
    "journalNote": "Textos sobre urbanismo, movilidad y datos públicos en Galicia.",
    "findJournal": "{n} en el diario",
    "read": "Leer",
    "journalSource": "Fuente",
    "journalCoverage": "Cobertura",
    "skipText": "Saltar al texto",
    "contents": "Contenido"
  },
  "en": {
    "intro": "Open maps and tools on public data, for Galicia.",
    "skip": "Skip to works",
    "sections": "Sections",
    "works": "Works",
    "archive": "Archive",
    "about": "About",
    "github": "GitHub",
    "archiveNote": "Tools behind the maps.",
    "redux": "Redux",
    "find": "Find",
    "findPlaceholder": "Title, place, data or tool",
    "findCount": "{n} of {total}",
    "findNone": "No match",
    "findArchive": "{n} found in the archive",
    "records": "Records",
    "record": "Project",
    "openSite": "Open the map",
    "openRecord": "Open",
    "aboutPage": "About",
    "dataPage": "Data",
    "code": "Code",
    "source": "Data",
    "built": "Built with",
    "updated": "Updated",
    "take": "Take",
    "more": "More",
    "overview": "Overview",
    "details": "Details",
    "continued": "{label}, continued",
    "pages": "Pages",
    "pageOf": "{i} / {n} · {label}",
    "previousPage": "Previous page",
    "nextPage": "Next page",
    "shotAlt": "Screenshot of {title}",
    "notice": "Independent civic work, built on public data. Based in Galicia.",
    "byline": "Made by <a href=\"{url}\">{name}</a>.",
    "sister": "<a href=\"{url}\">{name}</a> is the sister project, in New York.",
    "sourceCode": "Source code",
    "privacy": "No cookies or analytics.",
    "lostTab": "Not found",
    "lostTitle": "Our apologies.",
    "lostText": "This is, almost certainly, not the page you were looking for.",
    "lostHome": "Every project is listed on the <a href=\"{home}\">home page</a>.",
    "data": "Data",
    "map": "Map",
    "essay": "Essay",
    "site": "Site",
    "tools": "Tools",
    "journal": "Journal",
    "journalNote": "Writing on urbanism, mobility, and public data in Galicia.",
    "findJournal": "{n} found in the journal",
    "read": "Read",
    "journalSource": "Source",
    "journalCoverage": "Coverage",
    "skipText": "Skip to the text",
    "contents": "Contents"
  }
};
