/* Page copy for the site. One block per language; English is the only one filed. */
export const copy = {
  "en": {
    "intro": "Tools and maps built from public records in and around New York City.",
    "skip": "Skip to works",
    "language": "Language",
    "sections": "Sections",
    "works": "Works",
    "archive": "Archive",
    "about": "About",
    "archiveNote": "Earlier projects and tools.",
    "find": "Find",
    "findPlaceholder": "Title, place, data or tool",
    "findCount": "{n} of {total}",
    "findNone": "No match",
    "findArchive": "{n} found in the archive",
    "records": "Records",
    "record": "Project",
    "openSite": "Open site",
    "openRecord": "Open",
    "aboutPage": "About",
    "dataPage": "Data",
    "code": "Code",
    "source": "Data",
    "built": "Built with",
    "updated": "Updated",
    "take": "Take",
    "more": "More",
    "overview": "Overview",
    "details": "Details",
    "continued": "{label}, continued",
    "pages": "Pages",
    "pageOf": "{i} / {n} · {label}",
    "previousPage": "Previous page",
    "nextPage": "Next page",
    "shotAlt": "Screenshot of {title}",
    "notice": "<strong>Independent work.</strong> Not affiliated with or endorsed by the City of New York or the agencies whose data it uses.",
    "byline": "Made by <a href=\"{url}\">{name}</a>.",
    "sister": "<a href=\"{url}\">{name}</a> is the sister site, in Galicia.",
    "lostTab": "Not found",
    "lostTitle": "Our apologies.",
    "lostText": "This is, almost certainly, not the page you were looking for.",
    "lostHome": "Every project is listed on the <a href=\"{home}\">home page</a>.",
    "data": "Data",
    "map": "Map",
    "essay": "Essay",
    "site": "Site",
    "tools": "Tools",
    "journal": "Journal",
    "journalNote": "",
    "findJournal": "{n} found in the journal",
    "read": "Read",
    "journalSource": "Source",
    "journalCoverage": "Coverage",
    "skipText": "Skip to the text",
    "contents": "Contents"
  }
};
